# Generated by Django 5.0 on 2023-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='link-house', unique=True),
            preserve_default=False,
        ),
    ]
